import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Title from '../components/Title'
import Time from '../components/Time'
import DogFact from '../components/DogFact'
import Tips from '../components/Tips'
import CustomFooter from '../components/CustomFooter'

export default function Home() {
  return (
    <div className="flex flex-col h-screen w-screen items-center justify-center bg-slate-500">
      <Head>
        <title>Random Dog Facts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col md:w-2/4 lg:w-2/5 w-3/4 h-5/6 bg-[#ADD9D8] items-center rounded-xl">
        <Title />
        <Time />
        <DogFact />
        <Tips />
        <CustomFooter />
      </main>
    </div>
  )
}
